### PR TITLE
Removing cbcpy.

### LINKED ISSUE #41: Allow using LOGOS with newer versions of Python by removing cbcpy
**Is your feature request related to a problem? Please describe.**
cbcpy is not available on python versions newer than 3.7

**Describe the solution you'd like**
Remove cbcpy

**Additional context**
cbcpy was added to try and fix windows, but it doesn't work:
```
08-Aug-22 09:57:38 pyomo.opt            ERROR    Solver (cbc) returned non-zero return code (3221225781)

Traceback (most recent call last):

  File "C:\Git\opt\build_root\raven\plugins\LOGOS\src\logos_main.py", line 72, in <module>

    modelInstance.run()

  File "C:\Git\opt\build_root\raven\plugins\LOGOS\src\CapitalInvestments\PyomoModels\ModelBase.py", line 294, in run

    results = opt.solve(model, load_solutions=False, tee=self.tee, **{'use_signal_handling':False})

  File "C:\Users\cogljj\.conda\envs\raven_libraries\lib\site-packages\pyomo\opt\base\solvers.py", line 597, in solve

    "Solver (%s) did not exit normally" % self.name)

pyomo.common.errors.ApplicationError: Solver (cbc) did not exit normally
```

See for example: https://civet.inl.gov/job/1145673/

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

### PR DESCRIPTION
**Pull request by joshua-cogliati-inl**
--------
Pull Request Description
--------
##### What issue does this change request address?
Closes #41 

##### What are the significant changes in functionality due to this change request?
Removes cbcpy from windows.

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [x] 1. Review all computer code.
- [x] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual.
- [x] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [x] 4. Regression tests have to complete successfully.
- [x] 5. If significant functionality is added, there must be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test.
- [x] 6. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.

### CODE REVIEW

**Comment by joshua-cogliati-inl** [comment]
Note that you can see the results of running LOGOS in python 3.8 without cbcpy in: https://civet.inl.gov/job/1151586/

So with cbcpy ( https://civet.inl.gov/job/1145673/ ):
```
FAILED:

Failed C:\Git\opt\build_root\raven\plugins\LOGOS/tests\Scheduling\logos_rcpsp



PASSED: 28

SKIPPED: 46

FAILED: 1

... there were failed tests for plugin LOGOS!
```

Without cbcpy ( https://civet.inl.gov/job/1151586/ ):

```
FAILED:

Failed C:\Git\opt\build_root\raven\plugins\LOGOS/tests\Scheduling\logos_rcpsp



PASSED: 28

SKIPPED: 46

FAILED: 1

... there were failed tests for plugin LOGOS!
```

**Review by wangcj05 — APPROVED** [review]
PR looks good. Probably need to skip the logos_rcpsp test on windows since it is failing now because of no cbc solver.

**Comment by joshua-cogliati-inl** [comment]
Okay, I will add the skip.

**Review by wangcj05 — APPROVED** [review]

**Comment by wangcj05** [comment]
checklist is good, and tests are green.

**Comment by wangcj05** [comment]
@joshua-cogliati-inl Thanks a lot!

**Comment by joshua-cogliati-inl** [comment]
I just updated the submodule ID in https://github.com/idaholab/raven/pull/1933

**Pull request merged**
