### PR TITLE
use InputData and InputType to process xml input nodes

### LINKED ISSUE #9: Use of InputData in LOGOS ExternalModels
**Is your feature request related to a problem? Please describe.**
Some LOGOS models are inheriting from RAVEN ExternalModels.
These models are not using InputData in their initialization step.

**Describe the solution you'd like**
Convert LOGOS ExternalModels to deal with InputData

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by wangcj05**
--------
Pull Request Description
--------
##### What issue does this change request address? (Use "#" before the issue to link it, i.e., #42.)
close #9 
Update LOGOS External Models with RAVEN InputData and InputType for XML processing. 

##### What are the significant changes in functionality due to this change request?

----------------
For Change Control Board: Change Request Review
----------------
The following review must be completed by an authorized member of the Change Control Board.
- [ ] 1. Review all computer code.
- [ ] 2. If any changes occur to the input syntax, there must be an accompanying change to the user manual.
- [ ] 3. Make sure the Python code and commenting standards are respected (camelBack, etc.) - See on the [wiki](https://github.com/idaholab/raven/wiki/RAVEN-Code-Standards#python) for details.
- [ ] 4. Automated Tests should pass. 
- [ ] 5. If significant functionality is added, there must  be tests added to check this. Tests should cover all possible options.  Multiple short tests are preferred over one large test. 
- [ ] 6. If the change modifies or adds a requirement or a requirement based test case, the Change Control Board's Chair or designee also needs to approve the change.  The requirements and the requirements test shall be in sync.
- [ ] 7. The merge request must reference an issue.  If the issue is closed, the issue close checklist shall be done.
- [ ] 8. If an analytic test is changed/added is the the analytic documentation updated/added?

### CODE REVIEW

**Review by mandd — APPROVED** [review]

**Comment by mandd** [comment]
The edits, looks good to me. No comments.

**Comment by wangcj05** [comment]
Test results on my local machine: 

image

**Comment by wangcj05** [comment]
@mandd This PR is ready for you to review.

**Review by mandd — APPROVED** [review]

**Comment by mandd** [comment]
PR is good to me

**Pull request merged**
